# Generated by Django 3.1.7 on 2021-03-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geochats', '0005_anonymoususer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonymoususer',
            name='username',
            field=models.CharField(default='user', max_length=100),
        ),
    ]
