# Generated by Django 3.1.7 on 2021-03-10 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geochats', '0007_auto_20210305_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoususer',
            name='username',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.AlterField(
            model_name='anonymoususer',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='user', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geochats.anonymoususer')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='geochats.username'),
        ),
    ]
