# Generated by Django 3.1.7 on 2021-03-18 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('geochats', '0008_auto_20210310_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='username',
            name='user',
        ),
        migrations.AlterField(
            model_name='message',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.username'),
        ),
        migrations.DeleteModel(
            name='AnonymousUser',
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
