# Generated by Django 3.1.7 on 2021-03-27 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('geochats', '0010_auto_20210327_1550'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anonmessage',
            options={'ordering': ['-date']},
        ),
        migrations.AlterModelOptions(
            name='authmessage',
            options={'ordering': ['-date']},
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created', models.DateTimeField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
