# Generated by Django 3.1.7 on 2021-03-27 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geochats', '0012_auto_20210327_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geochats.message'),
        ),
        migrations.AlterField(
            model_name='authmessage',
            name='message',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='geochats.message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geochats.chat'),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
